import React, { useState, useEffect, useRef } from 'react';
import { Play, Shield, Loader2, BrainCircuit, Activity, Terminal as TerminalIcon, Clock, Layers, Target, Globe } from 'lucide-react';
import { PayloadLog, AttackMethod, WafStatus, WafProfile, AiModel } from '../types';

export const AttackConsole: React.FC = () => {
  const [isRunning, setIsRunning] = useState(false);
  const [targetUrl, setTargetUrl] = useState("http://localhost:8000/target/baseline"); // Default target
  const [attackType, setAttackType] = useState<"sqli" | "xss" | "file_upload" | "deserialization">("sqli");
  const [logs, setLogs] = useState<PayloadLog[]>([]);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [logs]);

  const startExperiment = async () => {
    if (!targetUrl) return;
    setIsRunning(true);
    setLogs([]); // Clear previous logs

    try {
      const response = await fetch('http://localhost:8000/api/attack/start', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          target_url: targetUrl,
          attack_type: attackType,
          llm_provider: "openai"
        }),
      });

      if (!response.ok) {
        throw new Error(`API Error: ${response.statusText}`);
      }

      const data = await response.json();
      console.log("Backend Response:", data);

      // Map backend structured logs to frontend format
      const newLogs: PayloadLog[] = data.structured_logs.map((log: any, index: number) => ({
        id: `log-${index}-${Date.now()}`,
        timestamp: log.timestamp,
        original: "N/A (Generated by Backend)",
        mutated: log.payload,
        method: AttackMethod.LLM_SEMANTIC, // Placeholder
        targetProfile: WafProfile.CUSTOM_GATEWAY, // Placeholder
        iteration: log.round,
        status: log.status === "BYPASSED" ? WafStatus.BYPASSED : WafStatus.BLOCKED,
        wafConfidence: log.code === 403 ? 99.9 : (log.code === 200 ? 0 : 50),
        reward: log.status === "BYPASSED" ? 10 : 0,
        reasoning: `${log.strategy} - ${log.reasoning}`,
        latency: 0, // Backend doesn't return latency per step yet
        modelUsed: AiModel.PRO
      }));

      // Simulate a sequence of logs appearing (optional, or just set all)
      // For now, just set them all at once or simple specific delay if we had streaming
      setLogs(newLogs);

    } catch (error) {
      console.error("Attack failed:", error);
      // Add an error log
      const errorLog: PayloadLog = {
        id: 'error',
        timestamp: new Date().toLocaleTimeString(),
        original: '-',
        mutated: 'ERROR CONNECTING TO BACKEND',
        method: AttackMethod.LLM_SEMANTIC,
        targetProfile: WafProfile.CUSTOM_GATEWAY,
        iteration: 0,
        status: WafStatus.BLOCKED,
        wafConfidence: 0,
        reward: 0,
        reasoning: error instanceof Error ? error.message : "Unknown Error",
        latency: 0,
        modelUsed: AiModel.PRO
      };
      setLogs([errorLog]);
    } finally {
      setIsRunning(false);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 h-[calc(100vh-140px)]">
      {/* Settings Panel */}
      <div className="bg-cyber-800 border border-cyber-700 rounded-xl p-5 flex flex-col gap-5 overflow-y-auto shadow-2xl">
        <div>
          <h3 className="text-white text-sm font-bold mb-4 flex items-center gap-2 border-b border-cyber-700 pb-2">
            <Layers className="w-4 h-4 text-cyber-accent" />
            Experiment Config
          </h3>

          <div className="space-y-4">
            {/* Target Selection */}
            <div>
              <label className="text-[10px] text-gray-500 font-bold uppercase mb-2 block tracking-tighter">Target System</label>
              <div className="space-y-2">
                <div className="grid grid-cols-1 gap-1">
                  <button
                    onClick={() => setTargetUrl("http://localhost:8000/target/baseline")}
                    className={`text-[9px] py-1 border rounded ${targetUrl.includes('baseline') ? 'bg-cyber-warning/20 border-cyber-warning text-cyber-warning' : 'border-cyber-700 text-gray-400'}`}
                  >
                    Baseline (Vulnerable Backend)
                  </button>
                </div>

                <div className="grid grid-cols-2 gap-1 mt-1">
                  <button
                    onClick={() => setTargetUrl("http://localhost:8081/target/baseline")}
                    className={`text-[9px] py-1 border rounded ${targetUrl.includes(':8081') ? 'bg-purple-500/20 border-purple-500 text-purple-400' : 'border-cyber-700 text-gray-400'}`}
                  >
                    🐳 Docker: ModSecurity (OWASP CRS)
                  </button>
                  <button
                    onClick={() => setTargetUrl("http://localhost:9443")}
                    className={`text-[9px] py-1 border rounded ${targetUrl.includes(':9443') ? 'bg-orange-500/20 border-orange-500 text-orange-400' : 'border-cyber-700 text-gray-400'}`}
                  >
                    🐳 Docker: SafeLine (AI WAF)
                  </button>
                </div>

                <div className="relative">
                  <input
                    type="text"
                    value={targetUrl}
                    onChange={(e) => setTargetUrl(e.target.value)}
                    className="w-full bg-cyber-900 border border-cyber-700 rounded-lg px-3 py-2 text-xs text-cyber-accent focus:border-cyber-accent outline-none font-mono"
                    placeholder="Custom URL..."
                  />
                  <Globe className="absolute right-3 top-2.5 w-3 h-3 text-gray-500" />
                </div>
              </div>
            </div>

            <div>
              <label className="text-[10px] text-gray-500 font-bold uppercase mb-2 block tracking-tighter">Attack Vector</label>
              <div className="grid grid-cols-2 gap-2">
                <button
                  onClick={() => setAttackType("sqli")}
                  className={`px-3 py-2 rounded-lg text-[10px] font-bold border transition-all flex flex-col items-center gap-1 ${attackType === "sqli" ? 'bg-cyber-accent/10 border-cyber-accent text-cyber-accent' : 'bg-cyber-900 border-cyber-700 text-gray-400'}`}
                >
                  SQL Injection
                </button>
                <button
                  onClick={() => setAttackType("xss")}
                  className={`px-3 py-2 rounded-lg text-[10px] font-bold border transition-all flex flex-col items-center gap-1 ${attackType === "xss" ? 'bg-cyber-accent/10 border-cyber-accent text-cyber-accent' : 'bg-cyber-900 border-cyber-700 text-gray-400'}`}
                >
                  XSS
                </button>
                <button
                  onClick={() => setAttackType("file_upload")}
                  className={`px-3 py-2 rounded-lg text-[10px] font-bold border transition-all flex flex-col items-center gap-1 ${attackType === "file_upload" ? 'bg-cyber-accent/10 border-cyber-accent text-cyber-accent' : 'bg-cyber-900 border-cyber-700 text-gray-400'}`}
                >
                  File Upload
                </button>
                <button
                  onClick={() => setAttackType("deserialization")}
                  className={`px-3 py-2 rounded-lg text-[10px] font-bold border transition-all flex flex-col items-center gap-1 ${attackType === "deserialization" ? 'bg-cyber-accent/10 border-cyber-accent text-cyber-accent' : 'bg-cyber-900 border-cyber-700 text-gray-400'}`}
                >
                  Deserialization
                </button>
              </div>
            </div>

            <div>
              <label className="text-[10px] text-gray-500 font-bold uppercase mb-2 block tracking-tighter">Backend Status</label>
              <div className="bg-cyber-900/50 p-3 rounded-lg border border-cyber-700/50">
                <div className="flex items-center gap-2 mb-1">
                  <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
                  <span className="text-[10px] text-gray-400 font-mono">API: ONLINE</span>
                </div>
                <div className="text-[9px] text-gray-600 font-mono pl-4">
                  Endpoint: /api/attack/start<br />
                  Mode: Plan-Gen-Verify
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-auto">
          <button
            onClick={startExperiment}
            disabled={isRunning || !targetUrl}
            className="w-full py-4 bg-cyber-accent text-cyber-900 font-bold rounded-xl hover:scale-[1.02] active:scale-95 transition-all flex items-center justify-center gap-2 shadow-[0_0_30px_rgba(0,240,255,0.3)] disabled:opacity-50 disabled:grayscale"
          >
            {isRunning ? <Loader2 className="w-5 h-5 animate-spin" /> : <Play className="w-5 h-5" />}
            INITIATE CLOSED-LOOP
          </button>
        </div>
      </div>

      {/* Output Console */}
      <div className="lg:col-span-3 bg-cyber-900 border border-cyber-700 rounded-xl overflow-hidden flex flex-col shadow-inner">
        <div className="bg-cyber-800 px-4 py-2 border-b border-cyber-700 flex justify-between items-center">
          <div className="flex items-center gap-3">
            <TerminalIcon className="w-3 h-3 text-cyber-accent" />
            <span className="text-[10px] font-mono text-gray-400 uppercase tracking-widest">Research://Live_Feed</span>
          </div>
          <div className="flex gap-2">
            <div className="w-2 h-2 rounded-full bg-red-500/50 animate-pulse"></div>
            <div className="w-2 h-2 rounded-full bg-yellow-500/50"></div>
            <div className="w-2 h-2 rounded-full bg-green-500/50"></div>
          </div>
        </div>

        <div className="flex-1 p-6 font-mono text-xs overflow-y-auto space-y-8 bg-[#0a0a0f] relative" ref={scrollRef}>
          {/* Background Grid Decoration */}
          <div className="absolute inset-0 opacity-[0.03] pointer-events-none" style={{ backgroundImage: 'radial-gradient(#00f0ff 1px, transparent 0)', backgroundSize: '24px 24px' }}></div>

          {logs.length === 0 && !isRunning && (
            <div className="h-full flex flex-col items-center justify-center text-gray-600 space-y-4">
              <Shield className="w-16 h-16 opacity-10" />
              <p className="text-xs uppercase tracking-[0.3em] opacity-30 italic">Awaiting Experiment Initialization...</p>
            </div>
          )}

          {logs.map((log) => (
            <div key={log.id} className="relative pl-6 border-l border-cyber-700 animate-in fade-in slide-in-from-left-2 duration-300">
              <div className="absolute left-[-5px] top-0 w-[9px] h-[9px] rounded-full bg-cyber-accent shadow-[0_0_8px_#00f0ff]"></div>

              <div className="flex items-center gap-4 mb-3">
                <span className="text-[9px] bg-cyber-accent/20 border border-cyber-accent/30 px-2 py-0.5 rounded text-cyber-accent font-bold uppercase tracking-tighter">ITR_{log.iteration}</span>
                <span className="text-gray-500 text-[9px] font-bold">[BACKEND_AGENT]</span>
                <span className="text-gray-600 text-[9px] font-mono">{log.timestamp}</span>
                <div className="flex items-center gap-1 text-cyber-warning text-[9px]">
                  <Clock className="w-3 h-3" />
                  Realtime
                </div>
              </div>

              <div className="space-y-4">
                <div className="bg-cyber-800/40 p-4 rounded-xl border border-cyber-700/50 backdrop-blur-sm">
                  <div className="text-[10px] uppercase font-black text-cyber-accent/70 mb-2 flex items-center gap-2">
                    <BrainCircuit className="w-4 h-4" />
                    Planner Logic & Verification
                  </div>
                  <p className="text-gray-300 italic text-[11px] leading-relaxed border-l-2 border-cyber-accent/20 pl-3">
                    {log.reasoning}
                  </p>
                </div>

                <div className="relative group">
                  <div className="bg-black/40 p-4 rounded-lg border border-cyber-700 font-mono text-cyber-success break-all select-all hover:border-cyber-accent transition-colors">
                    <span className="text-gray-600 mr-2 select-none">$</span>
                    {log.mutated}
                  </div>
                </div>

                <div className="flex items-center gap-4 pt-1">
                  <div className={`text-[10px] px-3 py-1 rounded-md font-bold border flex items-center gap-2 ${log.status === WafStatus.BYPASSED ? 'bg-cyber-success/10 border-cyber-success text-cyber-success shadow-[0_0_15px_rgba(5,255,161,0.1)]' : 'bg-cyber-danger/10 border-cyber-danger text-cyber-danger'
                    }`}>
                    <Activity className="w-3 h-3" />
                    {log.status}
                  </div>
                  <div className="flex-1 flex flex-col gap-1">
                    {/* Simplified confidence bar since we don't have simulated confidence anymore, relying on status code */}
                    <div className="flex justify-between text-[8px] text-gray-500 uppercase font-black">
                      <span>WAF_RESPONSE_CODE</span>
                      <span className={log.wafConfidence > 50 ? 'text-cyber-danger' : 'text-cyber-success'}>{log.wafConfidence > 90 ? '403 Forbidden' : '200 OK'}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}

          {isRunning && (
            <div className="flex items-center gap-4 text-cyber-accent p-5 bg-cyber-accent/5 border border-cyber-accent/10 rounded-xl">
              <div className="relative">
                <Loader2 className="w-6 h-6 animate-spin" />
                <div className="absolute inset-0 bg-cyber-accent/20 blur-lg animate-pulse"></div>
              </div>
              <div className="flex flex-col">
                <span className="text-[10px] font-black uppercase tracking-[0.2em] animate-pulse">Running Closed-Loop Attack...</span>
                <span className="text-[9px] text-gray-600 font-mono italic">Planner -{'>'} Generator -{'>'} Verifier -{'>'} Mutation</span>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};